SHOW DATABASES;
USE customer_behavior;

SHOW TABLES;

select * from customer LIMIT 20 ;


-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender ,SUM(purchase_amount) as revenue
FROM customer
group by gender ;



-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id from customer 
where discount_applied = "Yes" and purchase_amount > (select AVG(purchase_amount) from customer);


-- Q3. Which are the top 5 products with the highest average review rating?
select * from customer ;
select item_purchased,ROUND(avg(review_rating),2)
 from customer 
 group by item_purchased 
 order by  avg(review_rating) desc limit 5 ;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type,SUM(purchase_amount) as revenue
FROM customer
group by shipping_type ;

select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.


select subscription_status, avg(purchase_amount) 
from customer 
group by subscription_status order by avg(purchase_amount) desc ;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
select * from customer ;
with customer_type as 
(select customer_id, previous_purchases,
case 
when previous_purchases = 1 or 0 then "NEW"
when previous_purchases between  2 and  10  then "RETURNING"
else "LOYAL"
end as customer_segment from customer )
select customer_segment,count(*) from customer_type group by customer_segment ;

 
-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

 
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;
